### ISSUE TITLE
Incident data: size_primary# == 0 gives warning in sizecat_primary#

### ISSUE THREAD

**Issue by tsurudak** [Breast-Cancer-Risk-Prediction-Project/data-management#12]
Some of our pathologists have reported tumour diameters between 0 and 0.5mm (e.g. 0.2mm) - it's rare that this happens, but since the data dictionary asks for these measurements in mm, they have been rounded down to 0mm and are giving a warning in sizecat_primary#. 

Not sure if this is an issue if you want to fix, or if this is just a warning that we should accept on our end after having checked the cases :)

**Comment by tahearn** [comment]
I'm leaning towards keeping this as warning for studies to confirm the values are correct.
