### ISSUE TITLE
Crossrange2 waring for smoking_dur in Warning Rules.xlsx

### ISSUE THREAD

**Issue by tsurudak** [Breast-Cancer-Risk-Prediction-Project/data-management#14]
Cell H68 includes a check for whether smoking_dur is within the range of smoking_stop - smoking_init +- **2**, but the corresponding warning in cell T68 is "smoking_dur is more than the difference between smoking_init and smoking_stop +- **4** year window"

**Comment by tahearn** [comment]
Thanks! We've corrected the warning message
