### ISSUE TITLE
range waring for breastfeed_dur in Warning Rules.xlsx

### ISSUE THREAD

**Issue by tsurudak** [Breast-Cancer-Risk-Prediction-Project/data-management#15]
The valid range for breastfeed duration is 0-24 months for births 1-10 in breastfeed_dur_b#.
The valid upper limit for the overall breastfeed_dur variable is 84 months. Should this be increased to 240 months?

**Comment by tahearn** [comment]
Since most women have few pregnancies, we decided to go with 84 as the upper limit. We carried this threshold over from BCAC, which came up with 84 months based on the large amount of data shared with their consortium.
