### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by tsurudak** [Breast-Cancer-Risk-Prediction-Project/data-management#3]
@SrijonMukherjee - after commit [1a10216](https://github.com/Breast-Cancer-Risk-Prediction-Project/data-management/commit/1a102165214268df131fb2305cb469aa47fd9e7d), I am getting the following error when running BCRPP QC.R (specifically line 1350 (in my version) core.data.qc <- warnings_qc(params=...))

![image](https://github.com/Breast-Cancer-Risk-Prediction-Project/data-management/assets/7257474/1488844d-408c-4a44-94aa-ff13264694a3)

The result is that core.data.qc isn't created.

Traceback:
![image](https://github.com/Breast-Cancer-Risk-Prediction-Project/data-management/assets/7257474/c1a1834a-2e08-4f12-8700-69303349dd0d)

**Comment by SrijonMukherjee** [comment]
I just updated the rules. Let me know if the issue still occurs?

**Comment by SrijonMukherjee** [comment]
I think this was resolved? Let me know if not and I'll re-open the issue.
