### ISSUE TITLE
Error in Core Warning Rules

### ISSUE THREAD

**Issue by rfrost1** [Breast-Cancer-Risk-Prediction-Project/data-management#5]
There is a tiny error in the cell M49 of the warning rules, where there is an apostrophe after the written code. Causes the generation of bcrpp.core.warning.rules to stop. Also 666 is not showing as a valid value for alcohol_stop when I believe it should be.

**Comment by tsurudak** [comment]
I didn't see the apostrophe when I originally posted the issue, but I think this is a more concrete description of Issue #3

**Comment by SrijonMukherjee** [comment]
Thanks for the catch! I just edited, could you check if it's working now?

**Comment by tsurudak** [comment]
Tried to check today @SrijonMukherjee but I am getting stopped at an error in the Warning Rules that I think stems from cell C5.
"as" is written in the Valid Value Lower field, but I think it's expecting a number

![image](https://github.com/Breast-Cancer-Risk-Prediction-Project/data-management/assets/7257474/5c63787f-7ace-4c06-8e64-8812549b2322)

![image](https://github.com/Breast-Cancer-Risk-Prediction-Project/data-management/assets/7257474/5bc25b63-4d13-4c6c-a8f0-2ae93255fda5)

**Comment by SrijonMukherjee** [comment]
Sorry for the typo—this should be resolved now!
