### ISSUE TITLE
`Sub-Category` in QC Code

### ISSUE THREAD

**Issue by rfrost1** [Breast-Cancer-Risk-Prediction-Project/data-management#8]
The functions core_summary_report and incident_summary_report are both calling the column `Sub-Category` from the data dictionary, but I believe it has been replaced by Category as the dictionary has been split into sheets. Replacing with Category fixed the issue on my end

**Comment by SrijonMukherjee** [comment]
Good catch, Reuben! I just updated the code, this should be fixed now.
